### ISSUE TITLE
[FIX] 피드백 후 고쳐야할것들

### ISSUE THREAD

**Issue by sunghyun1356** [PuzzleU/puzzle-Server#112]
## 🛠 Issue

피드백 기반 수정
<br/>

## 📝 To-do

- [x] 팀 지원서 상세 구현
- [x] 누가 지원서 열람 권한이 있어야 하는지 정해야 함
- [x] - POST, PATCH 관련 API에서 글자 수 예외 처리
- [x] - 공모전 홈페이지 API: 하트 수, 공모전 포스터 url 추가
- [x] - 공모전 별 팀 리스트 필터링 기능 구현 (view 36)
- [x] - 공모전 별 팀 리스트에서 팀 매칭 수 추가
- [x] - 팀 모집글 작성 url 변경 competition/team/...
- [x] - 경험 GET 확인
- [x] - 유저 학력 리스트 GET API 추가
- [x]  대기중인 지원자에서 지원서의 상태/수락 같이 보내줘야 함.
- [x]  <알림> api 만들어야 함
- [x] - 지원서 리스트 열람/수락-거절/지원서 상세 열람: 팀 모집 공고 글 작성자만 가능하게 수정
- [x] - 퍼즐 ID 중복 처리하기
- [x] - 회원가입 optional 입학보다 졸업이 빠르면 선택 불가능하게 예외 처리
- [x] - 회원가입 optional experience_id 빼기
- [x] - 회원가입 동의 여부 저장
- [x] - 한 공모전에 대해서 한 개 모집글을 올릴 수 있도록 수정
- [x] - 지원도 한번만 가능하도록 수정
- [x] - 공모전 팀의 지원서 들은 글쓴이만 열람가능
- [x] - 로그인 유저만 열람가능

**Comment by sunghyun1356** [comment]
회원가입 동의 여부가 뭐야?

**Comment by 13155a1** [comment]
> 회원가입 동의 여부가 뭐야?

피그마 '로그인 2' 뷰에서 '혜택/이벤트 수신 동의' 이거! 유저 정보에 저장해놓아야 할 것 같아

**Comment by sunghyun1356** [comment]
수고했어요
