### ISSUE TITLE
[FEAT] 알람기능 구현

### ISSUE THREAD

**Issue by sunghyun1356** [PuzzleU/puzzle-Server#117]
## 🛠 Issue

피드백 기반 수정
<br/>

## 📝 To-do

- [x]  Entity
- [x] Controller
- [x] Repository
- [x] Service
- [x] Info
- [x] Test
- [ ] Notification Entity 변경(api 위주로 조작)
- [ ] 친구가 되었을때 보내기(그 사람의 url로 이동)
- [ ] 친구요청 받았을 때 요청(그 사람의 url로 이동)
- [ ] 내꺼에 누가 지원했으면 보내기 (내 팀의 소개글로 이동)
- [ ] 나의 지우너 현황이 바뀌었어요. 확인해보세요! (내 지원글로 이동)
- [ ] ?님에 의해 팀에 추가 되었습니다(그 팀으로 이동)
