### ISSUE TITLE
[FEAT] Repository 생성

### ISSUE THREAD

**Issue by 13155a1** [PuzzleU/puzzle-Server#29]
## 🛠 Issue

Repository를 생성합니다
<br/>

## 📝 To-do

- [x] Competition Repository 생성
- [x] Team  Repository 생성
- [x] TeamUser  Repository 생성
- [x] TeamLocationRelation  Repository 생성
- [x] Apply  Repository 생성
- [x] Like  Repository 생성
- [x] User  Repository 생성
- [x] University  Repository 생성
- [x] Major  Repository 생성
- [x] UserInterestRelation  Repository 생성
- [x] UserSkillsetRelation  Repository 생성
- [x] UserLocationRelation Repository 생성
- [x] Experience  Repository 생성
- [x] Position  Repository 생성
- [x] UserPosition  Repository 생성
- [x] Interest  Repository 생성
- [x] Location  Repository 생성
- [x] Skillset  Repository 생성
- [x] Friendship  Repository 생성
- [x] PositionApplyRelation  Repository 생성

**Comment by sunghyun1356** [comment]
수고하셨습니다
