### ISSUE TITLE
[FEAT] 스플레시 뷰에서 정해진 데이터 모두 넘겨주는 메서드 구현

### ISSUE THREAD

**Issue by 13155a1** [PuzzleU/puzzle-Server#59]
## 🛠 Issue

스플래스 뷰에서 사용자가 수정하지 않는, 모든 데이터를 넘겨주는 매서드를 구현합니다.
<br/>

## 📝 To-do

- [x] Position 리스트 service 구현
- [x] Interest 리스트 service 구현
- [x] Location 리스트 service 구현
- [x] Profile 리스트 service 구현
- [x] static data list controller 구현
- [x] 빈 리스트일 때 에러 설정

**Comment by sunghyun1356** [comment]
수고하셨습니다
