### ISSUE TITLE
[FEAT] Entity 생성

### ISSUE THREAD

**Issue by sunghyun1356** [PuzzleU/puzzle-Server#9]
## 🛠 Issue

Entity를 생성합니다
<br/>

## 📝 To-do

- [x] Competition Entity 구현
- [x] Team Entity 구현
- [x] TeamUser Entity 구현
- [x] TeamLocationRelation Entity 구현
- [x] Apply Entity 구현
- [x] Like Entity 구현
- [x] User Entity 구현
- [x] University Entity 구현
- [x] Major Entity 구현
- [x] UserInterestRelation Entity 구현
- [x] UserSkillsetRelation Entity 구현
- [x] UserLocationRelation Entity 구현
- [x] Experience Entity 구현
- [x] Position Entity 구현
- [x] UserPosition Entity 구현
- [x] Interest Entity 구현
- [x] Location Entity 구현
- [x] Skillset Entity 구현
- [x] Friendship Entity 구현
- [x] PositionApplyRelation Entity 구현

**Comment by sunghyun1356** [comment]
수고하셨습니다
